### PR TITLE
Static address calculation from dynamic address and memory map

### PR DESCRIPTION
**Pull request by gretay-js**
The example in #13  does not work for me, I just get `No location for f`.  
I think that the address calculation in `Owee_location.lookup` is missing something. This PR is an attempt to fix it. It fixes the above example, but I have not tested it on anything else, and in particular on any PIE executables, as I wanted to know what you think about this approach @let-def.

I think the translation of a dynamic address to static address has to take into account the static section address and offset, in addition to the dynamic segment address and offset. The PR assumes that any address that might appear in .debug_line will be in the text section, and so it just records the text section details during `extract_debug` along with the parsed entries.

### CODE REVIEW

**Comment by let-def** [comment]
Thanks. I think this is the right approach (I haven't checked all the details), I am open to merging this PR if you are ok.

**Comment by gretay-js** [comment]
It would be great, thank you!

**Comment by gretay-js** [comment]
ping.. has this PR been forgotten?

**Comment by let-def** [comment]
Yes, sorry. Thanks!

**Pull request merged**
