### PR TITLE
Replace interval tree by specialized interval map

### PR DESCRIPTION
**Pull request by let-def**
This PR implements the algorithm suggested in #23.
I am not sure if the performance are good enough and I only ran very simple tests.

@Xyene: could you assess the impact on performance? Is it solving the issue you reported?

### CODE REVIEW

**Comment by Xyene** [comment]
That was very fast, nice job :)

I threw it at some binaries on a couple of different machines. The types of speedups I'm seeing are e.g. 20s &rarr; 5s, which is substantially better. 3-4&times; improvement seems to be around the ballpark, regardless of executable size. I imagine there is some baseline overhead of just reading through the ELF binary; I haven't taken a new trace yet so I don't know what that is.

Some thoughts:

* It may be possible to eke out a bit more performance by switching from `Int64.t` to regular `int`s. I think that's valid for Owee's target architecture: the Linux kernel reserves the top few bits of address space, so all userspace pointers necessarily fit in an int63 (so we can lose the boxing).
* I think it'd possible to make `create` lazy, so that we don't need to pay the construction cost up front. When we `query` an address greater than what we've processed, we compute the delta in maps at that time. We save time if we never end up needing to `query` something near the end of the binary.

**Comment by let-def** [comment]
I just pushed an implementation using unboxed/tagged integers.
The initial sort probably has to be eager (unless addresses in DWARF are guaranteed to be in order... unsure).

Constructing the maps is just a left scan, that one can easily be done lazily.
Also, I wonder if the cumulative map would benefit from some pruning, as in most cases there should not be much overlap.

**Comment by let-def** [comment]
(In this case, maybe a scapegoat tree could help: accumulate junk, cleanup on rebalance)

**Comment by Xyene** [comment]
Awesome!

Some numbers:

- The changes in https://github.com/let-def/owee/pull/24/commits/528e9e37a6f25d135b8208a619d9293f83d3b36c bring the time down from 5s &rarr; 3s.
- Commenting out the map construction (to simulate it being lazy) brings the creation time down to 0.7s
- Commenting out the sort (just to see what it costs) then brings the creation time down to 0.5s (so costs 200ms, negligible)

In the magic-trace use-case, we immediately after launching present the user with a symbol fuzzy-finder (via `Owee_interval_map.iter`, after some indirection), and any time we would `query` would be after the user is out of the "hot path" and has Alt-tabbed out or something -- so having `create` be fast is useful there :)

I can see pruning the tree possibly being helpful in speeding things up. I wonder if it'd end up increasing memory usage from needing to reallocate more of the tree, or if that would even be noticeable.

**Comment by Xyene** [comment]
Yay, with the latest commit Owee is down to the promised 0.7s, 30&times; faster than the baseline :)

This patchset looks good to me, but I'm happy to run more benchmarks if you'd like to tweak it some more.

**Comment by let-def** [comment]
Thanks for the figures. I am testing on my laptop (the biggest binary is blender): original Owee was expensive, but now it is lost in noise, so I am relying on your tests :).
I have added lazy computation of maps. The sort can also be done on-demand, 200ms out of initialization path is not that bad.

If done cleverly, pruning should help a bit more. I have not yet decided how that sould be done. Maybe I will switch back to eager code path temporarily, to tune pruning.

**Comment by let-def** [comment]
(I will refrain from sorting on-demand: there is a risk of stale results if the user starts querying in the middle of `iter`...)

**Comment by let-def** [comment]
The latest addition might be a bit over-engineered but should be quite fast...
However, when I tested with blender, I discovered something interesting:
- most intervals look erroneous (maybe half of them where (0, 1)), these could be filtered, or interval with same bounds could be merged
- outside of this, there where almost no overlaps. The code could optimize for the case where there is a very small number of overlaps.

This is worth considering, though it might not be representative of all binaries.

**Comment by Xyene** [comment]
Awesome, we're down 3s &rarr; 2s when forcing the entire map to be "materialized" by performing one query at INT_MAX. Memory usage also improved by 25% (not that I think this matters, just throwing it up as a datapoint that the pruning definitely helped).

I think languages like OCaml are more likely to have overlaps than the C/C++ bits of Blender, since they encourage nesting functions/closures/etc. more.

**Comment by Xyene** [comment]
> The initial sort probably has to be eager (unless addresses in DWARF are guaranteed to be in order... unsure).

Empirically, it seems like they're not in order for code generated by `ocamlopt`.

> most intervals look erroneous (maybe half of them where (0, 1)), these could be filtered, or interval with same bounds could be merged

For some ballpark numbers: in a binary I'm looking at, we have 1.49m symbols, and there are 1.45m unique start bounds. So this effect seems small, at least there.

I also got some more numbers: a (~1 GiB) binary that used to take 47s to `create` now takes 1.4s.

**Comment by let-def** [comment]
If you still have some time for testing, in this version I switched back to a traditional balanced tree (weight-balanced, but I might try a height-balanced/AVL too) that is lazily pruning the tree during rebalance.
It has better performance on my setup.

**Comment by Xyene** [comment]
It's very speedy now :)

On the same binary that I made this claim:

> Awesome, we're down 3s → 2s when forcing the entire map to be "materialized" by performing one query at INT_MAX.

It now takes 0.95s to query INT_MAX. Just the `create` takes 0.7~0.8s. (This is user time, so it's not counting waiting for file I/O to complete. That's not taking too long considering the size, around 0.2s.)

**Comment by Xyene** [comment]
Just a heads up, we're hoping to tag a "1.0" magic-trace release in the next day or two and it'd be really cool to have this change in for that, but no worries if you want to work on it more / don't want to tag an opam release just yet / etc., we can tag a point release later.

**Comment by let-def** [comment]
I plan to release it tomorrow (in roughly ~28h)

**Comment by let-def** [comment]
Opam PR submitted https://github.com/ocaml/opam-repository/pull/21222

**Pull request merged**
