### PR TITLE
Parse elf notes for stapsdt probes and buildid

### PR DESCRIPTION
**Pull request by gretay-js**
I added examples that demonstrate the new features:

- read GNU buildid of ELF binary

- read SystemTap notes describing tracing probes available in ELF binary

### CODE REVIEW

**Comment by let-def** [comment]
Thank you, sorry for the delay.

**Comment by gretay-js** [comment]
It looks like the merge did not work in the right direction, I'm not sure how to fix it.

**Comment by let-def** [comment]
I did something wrong, but I don't understand when. Sorry. Master should be in a good state now.

**Comment by gretay-js** [comment]
Thank you!

**Pull request merged**
